In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [6]:
# Create our features
X = df.drop(columns="loan_status")

X = pd.get_dummies(df)

# Create our target
y = df [["loan_status"]]

In [7]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.994958,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.070831,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,1.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,1.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [8]:
# Check the balance of our target values
y.value_counts()

loan_status
low_risk       68470
high_risk        347
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [10]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_scaler = scaler.fit(X_train)
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [11]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
brf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=78) 
brf_model = brf_model.fit(X_train, y_train)
predictions = brf_model.predict(X_test)

In [12]:
# Calculated the balanced accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
acc_score = accuracy_score(y_test, predictions)

In [13]:
acc_score

0.9984888113920372

In [14]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)

In [15]:
cm

array([[   92,     0],
       [   26, 17087]])

In [16]:
# Print the imbalanced classification report
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           92            0
Actual 1           26        17087

In [17]:
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           92            0
Actual 1           26        17087

Accuracy Score : 0.9984888113920372
Classification Report
              precision    recall  f1-score   support

   high_risk       0.78      1.00      0.88        92
    low_risk       1.00      1.00      1.00     17113

    accuracy                           1.00     17205
   macro avg       0.89      1.00      0.94     17205
weighted avg       1.00      1.00      1.00     17205

In [18]:
# List the features sorted in descending order by feature importance
importances = brf_model.feature_importances_
importances

array([2.48995151e-03, 1.10201566e-02, 6.10778523e-03, 7.00867313e-03,
       6.93312731e-03, 9.32209613e-04, 5.26170175e-03, 3.44560265e-03,
       6.19342769e-04, 5.66171399e-03, 3.91263425e-03, 6.98475402e-03,
       5.93685512e-03, 3.78195503e-02, 3.48526484e-02, 3.45457477e-02,
       4.01851261e-02, 4.61949133e-03, 0.00000000e+00, 0.00000000e+00,
       3.32716514e-02, 2.07585677e-04, 0.00000000e+00, 0.00000000e+00,
       2.04646793e-03, 5.41611617e-03, 3.22165630e-03, 2.55022839e-03,
       1.51990466e-03, 2.58581012e-03, 5.38726885e-03, 4.57535674e-03,
       5.27630940e-03, 1.79957978e-03, 2.44957645e-03, 5.28613509e-03,
       5.98445815e-03, 3.38423928e-03, 2.93791267e-03, 1.91913968e-03,
       3.20715309e-03, 1.40174219e-03, 3.67288535e-03, 7.74671369e-03,
       5.83157346e-03, 1.12809411e-04, 0.00000000e+00, 4.71897830e-03,
       8.55747553e-03, 2.54694748e-03, 2.77084911e-03, 2.51316685e-03,
       2.80939170e-03, 6.79544796e-03, 7.96095511e-04, 4.64934770e-03,
       2.74356565e-03, 4.48380744e-03, 3.25845996e-03, 4.06919949e-03,
       2.19424468e-03, 3.19397719e-03, 2.09857375e-03, 3.46869634e-03,
       0.00000000e+00, 0.00000000e+00, 2.64159690e-04, 2.22742896e-03,
       5.41961253e-03, 1.86221162e-03, 4.30078905e-04, 0.00000000e+00,
       6.29795705e-03, 2.75118213e-03, 5.38768792e-03, 3.67915779e-03,
       1.85888020e-04, 8.68169052e-04, 3.83602801e-04, 4.95543711e-04,
       5.39914845e-04, 1.80189341e-03, 7.82725323e-04, 1.52849615e-03,
       1.01972939e-02, 4.88167862e-03, 2.80436938e-01, 2.72340280e-01,
       0.00000000e+00, 5.92712758e-04, 7.88436799e-05, 2.16162155e-03,
       1.41081149e-03, 4.76705611e-04, 7.19833610e-04, 0.00000000e+00,
       0.00000000e+00])

In [19]:
sorted(zip(brf_model.feature_importances_, X.columns), reverse=True)

[(0.280436938230135, 'loan_status_high_risk'),
 (0.27234028022118106, 'loan_status_low_risk'),
 (0.04018512610612609, 'total_rec_int'),
 (0.037819550303720674, 'total_pymnt'),
 (0.03485264842172196, 'total_pymnt_inv'),
 (0.03454574768319038, 'total_rec_prncp'),
 (0.03327165144079521, 'last_pymnt_amnt'),
 (0.011020156641910604, 'int_rate'),
 (0.01019729387032657, 'issue_d_Jan-2019'),
 (0.008557475531988957, 'mo_sin_old_rev_tl_op'),
 (0.007746713691809121, 'bc_open_to_buy'),
 (0.007008673134713329, 'annual_inc'),
 (0.006984754015321814, 'out_prncp'),
 (0.006933127309968143, 'dti'),
 (0.006795447960201199, 'mths_since_recent_inq'),
 (0.00629795705110388, 'tot_hi_cred_lim'),
 (0.006107785227427004, 'installment'),
 (0.005984458151490829, 'all_util'),
 (0.0059368551201325745, 'out_prncp_inv'),
 (0.005831573457721047, 'bc_util'),
 (0.005661713994650832, 'revol_bal'),
 (0.005419612526352336, 'pct_tl_nvr_dlq'),
 (0.005416116174268911, 'tot_cur_bal'),
 (0.005387687919204227, 'total_bc_limit'),
 (0.005387268853128252, 'mths_since_rcnt_il'),
 (0.005286135092954326, 'max_bal_bc'),
 (0.005276309404289842, 'il_util'),
 (0.005261701754935252, 'inq_last_6mths'),
 (0.004881678623957385, 'issue_d_Mar-2019'),
 (0.0047189783017856195, 'mo_sin_old_il_acct'),
 (0.004649347699352618, 'num_actv_bc_tl'),
 (0.004619491327515699, 'total_rec_late_fee'),
 (0.004575356735869568, 'total_bal_il'),
 (0.0044838074374538225, 'num_bc_sats'),
 (0.004069199490199398, 'num_il_tl'),
 (0.003912634253408343, 'total_acc'),
 (0.003679157788917246, 'total_il_high_credit_limit'),
 (0.003672885347386392, 'avg_cur_bal'),
 (0.003468696338713549, 'num_sats'),
 (0.003445602650616558, 'open_acc'),
 (0.003384239282187883, 'total_rev_hi_lim'),
 (0.003258459962985728, 'num_bc_tl'),
 (0.0032216563042119332, 'open_acc_6m'),
 (0.003207153088624697, 'inq_last_12m'),
 (0.0031939771889712763, 'num_rev_accts'),
 (0.0029379126667227738, 'inq_fi'),
 (0.002809391700625062, 'mths_since_recent_bc'),
 (0.002770849114619457, 'mo_sin_rcnt_tl'),
 (0.0027511821271234676, 'total_bal_ex_mort'),
 (0.002743565647799002, 'num_actv_rev_tl'),
 (0.002585810115531731, 'open_il_24m'),
 (0.0025502283889371523, 'open_act_il'),
 (0.0025469474781899793, 'mo_sin_rcnt_rev_tl_op'),
 (0.002513166854853292, 'mort_acc'),
 (0.0024899515079005222, 'loan_amnt'),
 (0.002449576454944295, 'open_rv_24m'),
 (0.00222742896254039, 'num_tl_op_past_12m'),
 (0.00219424467917302, 'num_op_rev_tl'),
 (0.002161621553640552, 'next_pymnt_d_Apr-2019'),
 (0.0020985737495735823, 'num_rev_tl_bal_gt_0'),
 (0.0020464679261112, 'tot_coll_amt'),
 (0.0019191396784647844, 'total_cu_tl'),
 (0.0018622116152693447, 'percent_bc_gt_75'),
 (0.0018018934105863346, 'verification_status_Source Verified'),
 (0.001799579781730008, 'open_rv_12m'),
 (0.0015284961491386403, 'issue_d_Feb-2019'),
 (0.0015199046591489152, 'open_il_12m'),
 (0.0014108114904054752, 'next_pymnt_d_May-2019'),
 (0.0014017421865828617, 'acc_open_past_24mths'),
 (0.0009322096125947862, 'delinq_2yrs'),
 (0.0008681690518606591, 'home_ownership_MORTGAGE'),
 (0.0007960955109475636, 'num_accts_ever_120_pd'),
 (0.0007827253232235394, 'verification_status_Verified'),
 (0.0007198336103690075, 'application_type_Joint App'),
 (0.0006193427689915445, 'pub_rec'),
 (0.0005927127580909095, 'initial_list_status_f'),
 (0.0005399148452378756, 'verification_status_Not Verified'),
 (0.0004955437113904381, 'home_ownership_RENT'),
 (0.00047670561099616914, 'application_type_Individual'),
 (0.00043007890464711625, 'pub_rec_bankruptcies'),
 (0.0003836028007823169, 'home_ownership_OWN'),
 (0.00026415969013196425, 'num_tl_90g_dpd_24m'),
 (0.00020758567671962637, 'collections_12_mths_ex_med'),
 (0.00018588802047556546, 'home_ownership_ANY'),
 (0.00011280941112414128, 'chargeoff_within_12_mths'),
 (7.884367987784814e-05, 'initial_list_status_w'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [23]:
X_train

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
12386,20000.0,0.1557,481.81,80000.0,24.30,0.0,0.0,18.0,0.0,9159.0,...,1,1,0,1,1,0,1,0,1,1
39432,1000.0,0.1180,33.12,31000.0,13.70,0.0,0.0,6.0,0.0,1150.0,...,1,1,1,0,1,0,1,0,1,1
14198,10000.0,0.1502,238.01,80000.0,23.18,0.0,1.0,12.0,0.0,2444.0,...,1,1,0,1,1,0,1,0,1,1
4777,5000.0,0.0756,155.67,100000.0,23.54,0.0,0.0,12.0,0.0,10440.0,...,1,1,0,1,1,0,1,0,1,1
17746,25000.0,0.1797,634.43,105000.0,10.95,0.0,0.0,8.0,0.0,23512.0,...,1,1,0,1,1,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66244,32000.0,0.1502,761.62,112000.0,26.21,0.0,0.0,25.0,0.0,71180.0,...,1,1,0,1,1,0,1,0,1,1
52748,5000.0,0.1298,168.43,52000.0,30.67,0.0,0.0,12.0,1.0,19836.0,...,1,1,0,1,0,1,1,0,1,1
3476,23000.0,0.1033,492.43,110000.0,21.62,0.0,0.0,12.0,0.0,25902.0,...,1,1,0,1,0,1,1,0,1,1
37405,24000.0,0.1033,513.84,160000.0,19.09,1.0,0.0,10.0,0.0,4896.0,...,1,1,0,1,0,1,1,0,1,1
16854,5000.0,0.1072,163.04,60000.0,11.12,0.0,1.0,5.0,0.0,3231.0,...,1,1,0,1,1,0,1,0,1,1

In [24]:
y_train

      loan_status
12386    low_risk
39432    low_risk
14198    low_risk
4777     low_risk
17746    low_risk
...           ...
66244    low_risk
52748    low_risk
3476     low_risk
37405    low_risk
16854    low_risk

[51612 rows x 1 columns]

In [25]:
from imblearn.ensemble import EasyEnsembleClassifier 

# X_train_scaled, X_test_scaled, y_train, y_test = train_test_split(X, y,
#                                                     random_state=0)
eec = EasyEnsembleClassifier(n_estimators = 100, random_state=78)
eec.fit(X_train, y_train)

AttributeError: 'EasyEnsembleClassifier' object has no attribute 'n_features_in_'

In [ ]:
y_pred = eec.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred_scaled))

In [ ]:
# # Train the EasyEnsembleClassifier
# from imblearn.ensemble import EasyEnsembleClassifier
# from collections import Counter
# from sklearn.datasets import make_classification
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import confusion_matrix

# #X, y = make_classification(n_classes=2, class_sep=2,
# #weights=[0.1, 0.9], n_informative=3, n_redundant=1, flip_y=0,
# #n_features=20, n_clusters_per_class=1, n_samples=1000, random_state=10)
# #print('Original dataset shape %s' % Counter(y))
# #X_train, X_test, y_train, y_test = train_test_split(X, y,
# #                                                    random_state=0)

# ez_model = EasyEnsembleClassifier(base_estimator=None, n_estimators=100, n_jobs=1, random_state=1, 
#                                    replacement=False, sampling_strategy='auto', verbose=0, 
#                                    warm_start=False)

# ez_model = ez_model.fit(X_train, y_train)

In [ ]:
ez_y_pred = ez_model.predict(X_test_scaled)

In [ ]:
# Calculated the balanced accuracy score
acc_score = accuracy_score(y_test, predictions)

In [ ]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

In [ ]:
# Print the imbalanced classification report
# YOUR CODE HERE

In [ ]:
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))